// <auto-generated />
namespace CoffeeRoasterDesktopBackground
{
    public class Configuration
    {
        public string IpAddress { get; set; }
        public int PortNumber { get; set; }
        public string LogFileDatabaseDirectory { get; set; }
    }
}
